// Mocks generated by Mockito 5.4.6 from annotations
// in desby_app/test/features/marketplace/fabric_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:desby_app/core/error/failures.dart' as _i4;
import 'package:desby_app/features/marketplace/domain/entities/fabric.dart'
    as _i5;
import 'package:desby_app/features/marketplace/domain/repositories/fabric_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FabricRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFabricRepository extends _i1.Mock implements _i2.FabricRepository {
  MockFabricRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void>> uploadFabric(_i5.Fabric? fabric) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFabric, [fabric]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#uploadFabric, [fabric]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> updateFabric(_i5.Fabric? fabric) =>
      (super.noSuchMethod(
            Invocation.method(#updateFabric, [fabric]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateFabric, [fabric]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteFabric(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFabric, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteFabric, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Stream<List<_i5.Fabric>> streamCatalog({
    String? category,
    String? sellerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamCatalog, [], {
              #category: category,
              #sellerId: sellerId,
            }),
            returnValue: _i3.Stream<List<_i5.Fabric>>.empty(),
          )
          as _i3.Stream<List<_i5.Fabric>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Fabric>>> getSellerInventory(
    String? sellerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSellerInventory, [sellerId]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Fabric>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Fabric>>>(
                this,
                Invocation.method(#getSellerInventory, [sellerId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Fabric>>>);

  @override
  _i3.Future<_i4.Result<_i5.Fabric>> getFabricById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFabricById, [id]),
            returnValue: _i3.Future<_i4.Result<_i5.Fabric>>.value(
              _i6.dummyValue<_i4.Result<_i5.Fabric>>(
                this,
                Invocation.method(#getFabricById, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Fabric>>);

  @override
  _i3.Future<_i4.Result<Map<String, dynamic>>> getMerchantStats(
    String? merchantId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMerchantStats, [merchantId]),
            returnValue: _i3.Future<_i4.Result<Map<String, dynamic>>>.value(
              _i6.dummyValue<_i4.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#getMerchantStats, [merchantId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<Map<String, dynamic>>>);
}
