// Mocks generated by Mockito 5.4.6 from annotations
// in desby_app/test/features/orders/order_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:desby_app/core/error/failures.dart' as _i4;
import 'package:desby_app/features/orders/domain/entities/order.dart' as _i5;
import 'package:desby_app/features/orders/domain/repositories/order_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i2.OrderRepository {
  MockOrderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.OrderEntity>>> getOrders({
    _i5.OrderStatus? status,
    String? clientId,
    String? tailorId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrders, [], {
              #status: status,
              #clientId: clientId,
              #tailorId: tailorId,
            }),
            returnValue: _i3.Future<_i4.Result<List<_i5.OrderEntity>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.OrderEntity>>>(
                this,
                Invocation.method(#getOrders, [], {
                  #status: status,
                  #clientId: clientId,
                  #tailorId: tailorId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.OrderEntity>>>);

  @override
  _i3.Future<_i4.Result<_i5.OrderEntity>> getOrderById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderById, [id]),
            returnValue: _i3.Future<_i4.Result<_i5.OrderEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.OrderEntity>>(
                this,
                Invocation.method(#getOrderById, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.OrderEntity>>);

  @override
  _i3.Future<_i4.Result<_i5.OrderEntity>> createOrder(_i5.OrderEntity? order) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [order]),
            returnValue: _i3.Future<_i4.Result<_i5.OrderEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.OrderEntity>>(
                this,
                Invocation.method(#createOrder, [order]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.OrderEntity>>);

  @override
  _i3.Future<_i4.Result<_i5.OrderEntity>> updateOrderStatus(
    String? id,
    _i5.OrderStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateOrderStatus, [id, status]),
            returnValue: _i3.Future<_i4.Result<_i5.OrderEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.OrderEntity>>(
                this,
                Invocation.method(#updateOrderStatus, [id, status]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.OrderEntity>>);

  @override
  _i3.Future<_i4.Result<void>> deleteOrder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOrder, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteOrder, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
