// Mocks generated by Mockito 5.4.6 from annotations
// in desby_app/test/features/tailor/tailor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:desby_app/core/error/failures.dart' as _i4;
import 'package:desby_app/features/apprenticeship/domain/entities/apprentice_module.dart'
    as _i8;
import 'package:desby_app/features/apprenticeship/domain/entities/apprentice_task.dart'
    as _i7;
import 'package:desby_app/features/apprenticeship/domain/entities/apprenticeship.dart'
    as _i5;
import 'package:desby_app/features/apprenticeship/domain/repositories/apprenticeship_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ApprenticeshipRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApprenticeshipRepository extends _i1.Mock
    implements _i2.ApprenticeshipRepository {
  MockApprenticeshipRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Apprenticeship>>> getApprenticeships(
    String? tailorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getApprenticeships, [tailorId]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Apprenticeship>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Apprenticeship>>>(
                this,
                Invocation.method(#getApprenticeships, [tailorId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Apprenticeship>>>);

  @override
  _i3.Future<_i4.Result<_i5.Apprenticeship?>> getApprenticeship(
    String? apprenticeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getApprenticeship, [apprenticeId]),
            returnValue: _i3.Future<_i4.Result<_i5.Apprenticeship?>>.value(
              _i6.dummyValue<_i4.Result<_i5.Apprenticeship?>>(
                this,
                Invocation.method(#getApprenticeship, [apprenticeId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Apprenticeship?>>);

  @override
  _i3.Future<_i4.Result<_i5.Apprenticeship>> createApprenticeship(
    _i5.Apprenticeship? apprenticeship,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createApprenticeship, [apprenticeship]),
            returnValue: _i3.Future<_i4.Result<_i5.Apprenticeship>>.value(
              _i6.dummyValue<_i4.Result<_i5.Apprenticeship>>(
                this,
                Invocation.method(#createApprenticeship, [apprenticeship]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Apprenticeship>>);

  @override
  _i3.Future<_i4.Result<_i5.Apprenticeship>> updateApprenticeship(
    _i5.Apprenticeship? apprenticeship,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateApprenticeship, [apprenticeship]),
            returnValue: _i3.Future<_i4.Result<_i5.Apprenticeship>>.value(
              _i6.dummyValue<_i4.Result<_i5.Apprenticeship>>(
                this,
                Invocation.method(#updateApprenticeship, [apprenticeship]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Apprenticeship>>);

  @override
  _i3.Future<_i4.Result<List<_i7.ApprenticeTask>>> getApprenticeTasks(
    String? apprenticeshipId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getApprenticeTasks, [apprenticeshipId]),
            returnValue: _i3.Future<_i4.Result<List<_i7.ApprenticeTask>>>.value(
              _i6.dummyValue<_i4.Result<List<_i7.ApprenticeTask>>>(
                this,
                Invocation.method(#getApprenticeTasks, [apprenticeshipId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i7.ApprenticeTask>>>);

  @override
  _i3.Future<_i4.Result<_i7.ApprenticeTask>> createTask(
    _i7.ApprenticeTask? task,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [task]),
            returnValue: _i3.Future<_i4.Result<_i7.ApprenticeTask>>.value(
              _i6.dummyValue<_i4.Result<_i7.ApprenticeTask>>(
                this,
                Invocation.method(#createTask, [task]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i7.ApprenticeTask>>);

  @override
  _i3.Future<_i4.Result<_i7.ApprenticeTask>> updateTask(
    _i7.ApprenticeTask? task,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i3.Future<_i4.Result<_i7.ApprenticeTask>>.value(
              _i6.dummyValue<_i4.Result<_i7.ApprenticeTask>>(
                this,
                Invocation.method(#updateTask, [task]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i7.ApprenticeTask>>);

  @override
  _i3.Future<_i4.Result<List<_i8.ApprenticeModule>>> getCurriculum() =>
      (super.noSuchMethod(
            Invocation.method(#getCurriculum, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i8.ApprenticeModule>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i8.ApprenticeModule>>>(
                    this,
                    Invocation.method(#getCurriculum, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i8.ApprenticeModule>>>);

  @override
  _i3.Future<_i4.Result<List<_i8.ApprenticeLesson>>> getLessons(
    String? moduleId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLessons, [moduleId]),
            returnValue:
                _i3.Future<_i4.Result<List<_i8.ApprenticeLesson>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i8.ApprenticeLesson>>>(
                    this,
                    Invocation.method(#getLessons, [moduleId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i8.ApprenticeLesson>>>);

  @override
  _i3.Future<_i4.Result<_i8.ApprenticeLesson>> getLessonById(
    String? lessonId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLessonById, [lessonId]),
            returnValue: _i3.Future<_i4.Result<_i8.ApprenticeLesson>>.value(
              _i6.dummyValue<_i4.Result<_i8.ApprenticeLesson>>(
                this,
                Invocation.method(#getLessonById, [lessonId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.ApprenticeLesson>>);
}
