/// Complete Nigerian Local Government Areas (LGAs) Database
/// Data includes all 774 LGAs across 36 states and FCT
/// Organized hierarchically by State -> LGA -> Headquarters
library;

class NigeriaLgaData {
  /// List of all Nigerian states and FCT
  static const List<String> states = [
    'Abia',
    'Adamawa',
    'Akwa Ibom',
    'Anambra',
    'Bauchi',
    'Bayelsa',
    'Benue',
    'Borno',
    'Cross River',
    'Delta',
    'Ebonyi',
    'Edo',
    'Ekiti',
    'Enugu',
    'FCT',
    'Gombe',
    'Imo',
    'Jigawa',
    'Kaduna',
    'Kano',
    'Katsina',
    'Kebbi',
    'Kogi',
    'Kwara',
    'Lagos',
    'Nasarawa',
    'Niger',
    'Ogun',
    'Ondo',
    'Osun',
    'Oyo',
    'Plateau',
    'Rivers',
    'Sokoto',
    'Taraba',
    'Yobe',
    'Zamfara',
  ];

  /// Map of all LGAs by state
  /// Structure: State -> List of (LGA Name, Headquarters)
  static const Map<String, List<Map<String, String>>> lgasByState = {
    'Abia': [
      {'name': 'Aba North', 'headquarters': 'Eziama'},
      {'name': 'Aba South', 'headquarters': 'Aba'},
      {'name': 'Arochukwu', 'headquarters': 'Arochukwu'},
      {'name': 'Bende', 'headquarters': 'Bende'},
      {'name': 'Ikwuano', 'headquarters': 'Isiala Oboro'},
      {'name': 'Isiala Ngwa North', 'headquarters': 'Isiala Ngwa'},
      {'name': 'Isiala Ngwa South', 'headquarters': 'Isiala Ngwa'},
      {'name': 'Isuikwuato', 'headquarters': 'Uturu'},
      {'name': 'Obi Ngwa', 'headquarters': 'Ahiaba'},
      {'name': 'Ohafia', 'headquarters': 'Ohafia'},
      {'name': 'Osisioma Ngwa', 'headquarters': 'Aba'},
      {'name': 'Ugwunagbo', 'headquarters': 'Umuokereke'},
      {'name': 'Ukwa East', 'headquarters': 'Akwete'},
      {'name': 'Ukwa West', 'headquarters': 'Oke Ikpe'},
      {'name': 'Umuahia North', 'headquarters': 'Ibeku'},
      {'name': 'Umuahia South', 'headquarters': 'Ubakala'},
      {'name': 'Umu Nneochi', 'headquarters': 'Ndi Okereke Abia'},
    ],
    'Adamawa': [
      {'name': 'Demsa', 'headquarters': 'Demsa'},
      {'name': 'Fufore', 'headquarters': 'Fufore'},
      {'name': 'Ganye', 'headquarters': 'Ganye'},
      {'name': 'Gayuk', 'headquarters': 'Gayuk'},
      {'name': 'Gombi', 'headquarters': 'Gombi'},
      {'name': 'Grie', 'headquarters': 'Grie'},
      {'name': 'Hong', 'headquarters': 'Hong'},
      {'name': 'Jada', 'headquarters': 'Jada'},
      {'name': 'Lamurde', 'headquarters': 'Lamurde'},
      {'name': 'Madagali', 'headquarters': 'Madagali'},
      {'name': 'Maiha', 'headquarters': 'Maiha'},
      {'name': 'Mayo-Belwa', 'headquarters': 'Mayo-Belwa'},
      {'name': 'Michika', 'headquarters': 'Michika'},
      {'name': 'Mubi North', 'headquarters': 'Mubi'},
      {'name': 'Mubi South', 'headquarters': 'Gella'},
      {'name': 'Numan', 'headquarters': 'Numan'},
      {'name': 'Shelleng', 'headquarters': 'Shelleng'},
      {'name': 'Song', 'headquarters': 'Song'},
      {'name': 'Toungo', 'headquarters': 'Toungo'},
      {'name': 'Yola North', 'headquarters': 'Jimeta'},
      {'name': 'Yola South', 'headquarters': 'Yola'},
    ],
    'Akwa Ibom': [
      {'name': 'Abak', 'headquarters': 'Abak'},
      {'name': 'Eastern Obolo', 'headquarters': 'Okoroete'},
      {'name': 'Eket', 'headquarters': 'Eket'},
      {'name': 'Esit Eket', 'headquarters': 'Uquo'},
      {'name': 'Essien Udim', 'headquarters': 'Afaha Ikot Ebak'},
      {'name': 'Etim Ekpo', 'headquarters': 'Etim Ekpo'},
      {'name': 'Etinan', 'headquarters': 'Etinan'},
      {'name': 'Ibeno', 'headquarters': 'Ibeno'},
      {'name': 'Ibesikpo Asutan', 'headquarters': 'Ibesikpo'},
      {'name': 'Ibiono-Ibom', 'headquarters': 'Ibiono Ibom'},
      {'name': 'Ika', 'headquarters': 'Urua Inyang'},
      {'name': 'Ikono', 'headquarters': 'Ibiaku Ntok Okpo'},
      {'name': 'Ikot Abasi', 'headquarters': 'Ikot Abasi'},
      {'name': 'Ikot Ekpene', 'headquarters': 'Ikot Ekpene'},
      {'name': 'Ini', 'headquarters': 'Ikot Ekwere'},
      {'name': 'Itu', 'headquarters': 'Itu'},
      {'name': 'Mbo', 'headquarters': 'Enwang'},
      {'name': 'Mkpat-Enin', 'headquarters': 'Mkpat Enin'},
      {'name': 'Nsit-Atai', 'headquarters': 'Odot'},
      {'name': 'Nsit-Ibom', 'headquarters': 'Afaha Offiong'},
      {'name': 'Nsit-Ubium', 'headquarters': 'Ikot Edibon'},
      {'name': 'Obot Akara', 'headquarters': 'Nto Edino'},
      {'name': 'Okobo', 'headquarters': 'Okat Okobo'},
      {'name': 'Onna', 'headquarters': 'Abat'},
      {'name': 'Oron', 'headquarters': 'Oron'},
      {'name': 'Oruk Anam', 'headquarters': 'Ikot Ibritam'},
      {'name': 'Udung-Uko', 'headquarters': 'Udung Uko'},
      {'name': 'Ukanafun', 'headquarters': 'Ikot Akpa Nkuk'},
      {'name': 'Uruan', 'headquarters': 'Idu Uruan'},
      {'name': 'Urue-Offong/Oruko', 'headquarters': 'Urue Offong'},
      {'name': 'Uyo', 'headquarters': 'Uyo'},
    ],
    'Anambra': [
      {'name': 'Aguata', 'headquarters': 'Aguata'},
      {'name': 'Anambra East', 'headquarters': 'Nando'},
      {'name': 'Anambra West', 'headquarters': 'Nzam'},
      {'name': 'Anaocha', 'headquarters': 'Neni'},
      {'name': 'Awka North', 'headquarters': 'Achalla'},
      {'name': 'Awka South', 'headquarters': 'Awka'},
      {'name': 'Ayamelum', 'headquarters': 'Anaku'},
      {'name': 'Dunukofia', 'headquarters': 'Ukpo'},
      {'name': 'Ekwusigo', 'headquarters': 'Ozubulu'},
      {'name': 'Idemili North', 'headquarters': 'Ogidi'},
      {'name': 'Idemili South', 'headquarters': 'Ojoto'},
      {'name': 'Ihiala', 'headquarters': 'Ihiala'},
      {'name': 'Njikoka', 'headquarters': 'Abagana'},
      {'name': 'Nnewi North', 'headquarters': 'Nnewi'},
      {'name': 'Nnewi South', 'headquarters': 'Ukpor'},
      {'name': 'Ogbaru', 'headquarters': 'Atani'},
      {'name': 'Onitsha North', 'headquarters': 'Onitsha'},
      {'name': 'Onitsha South', 'headquarters': 'Onitsha'},
      {'name': 'Orumba North', 'headquarters': 'Ajalli'},
      {'name': 'Orumba South', 'headquarters': 'Umunze'},
      {'name': 'Oyi', 'headquarters': 'Nteje'},
    ],
    'Bauchi': [
      {'name': 'Alkaleri', 'headquarters': 'Alkaleri'},
      {'name': 'Bauchi', 'headquarters': 'Bauchi'},
      {'name': 'Bogoro', 'headquarters': 'Bogoro'},
      {'name': 'Damban', 'headquarters': 'Damban'},
      {'name': 'Darazo', 'headquarters': 'Darazo'},
      {'name': 'Dass', 'headquarters': 'Dass'},
      {'name': 'Gamawa', 'headquarters': 'Gamawa'},
      {'name': 'Ganjuwa', 'headquarters': 'Ganjuwa'},
      {'name': 'Giade', 'headquarters': 'Giade'},
      {'name': 'Itas/Gadau', 'headquarters': 'Itas'},
      {'name': 'Jama\'are', 'headquarters': 'Jama\'are'},
      {'name': 'Katagum', 'headquarters': 'Azare'},
      {'name': 'Kirfi', 'headquarters': 'Kirfi'},
      {'name': 'Misau', 'headquarters': 'Misau'},
      {'name': 'Ningi', 'headquarters': 'Ningi'},
      {'name': 'Shira', 'headquarters': 'Shira'},
      {'name': 'Tafawa Balewa', 'headquarters': 'Tafawa Balewa'},
      {'name': 'Toro', 'headquarters': 'Toro'},
      {'name': 'Warji', 'headquarters': 'Warji'},
      {'name': 'Zaki', 'headquarters': 'Zaki'},
    ],
    'Bayelsa': [
      {'name': 'Brass', 'headquarters': 'Twon-Brass'},
      {'name': 'Ekeremor', 'headquarters': 'Ekeremor'},
      {'name': 'Kolokuma/Opokuma', 'headquarters': 'Kaiama'},
      {'name': 'Nembe', 'headquarters': 'Nembe'},
      {'name': 'Ogbia', 'headquarters': 'Ogbia'},
      {'name': 'Sagbama', 'headquarters': 'Sagbama'},
      {'name': 'Southern Ijaw', 'headquarters': 'Oporoma'},
      {'name': 'Yenagoa', 'headquarters': 'Yenagoa'},
    ],
    'Benue': [
      {'name': 'Ado', 'headquarters': 'Igumale'},
      {'name': 'Agatu', 'headquarters': 'Obagaji'},
      {'name': 'Apa', 'headquarters': 'Ugbokpo'},
      {'name': 'Buruku', 'headquarters': 'Buruku'},
      {'name': 'Gboko', 'headquarters': 'Gboko'},
      {'name': 'Guma', 'headquarters': 'Gbajimba'},
      {'name': 'Gwer East', 'headquarters': 'Aliade'},
      {'name': 'Gwer West', 'headquarters': 'Naka'},
      {'name': 'Katsina-Ala', 'headquarters': 'Katsina-Ala'},
      {'name': 'Konshisha', 'headquarters': 'Tse-Agberagba'},
      {'name': 'Kwande', 'headquarters': 'Adikpo'},
      {'name': 'Logo', 'headquarters': 'Ugba'},
      {'name': 'Makurdi', 'headquarters': 'Makurdi'},
      {'name': 'Obi', 'headquarters': 'Obi'},
      {'name': 'Ogbadibo', 'headquarters': 'Otukpo'},
      {'name': 'Ohimini', 'headquarters': 'Idekpa'},
      {'name': 'Oju', 'headquarters': 'Oju'},
      {'name': 'Okpokwu', 'headquarters': 'Okpoga'},
      {'name': 'Otukpo', 'headquarters': 'Otukpo'},
      {'name': 'Tarka', 'headquarters': 'Wannune'},
      {'name': 'Ukum', 'headquarters': 'Sankera'},
      {'name': 'Ushongo', 'headquarters': 'Lessel'},
      {'name': 'Vandeikya', 'headquarters': 'Vandeikya'},
    ],
    'Borno': [
      {'name': 'Abadam', 'headquarters': 'Abadam'},
      {'name': 'Askira/Uba', 'headquarters': 'Askira'},
      {'name': 'Bama', 'headquarters': 'Bama'},
      {'name': 'Bayo', 'headquarters': 'Bayo'},
      {'name': 'Biu', 'headquarters': 'Biu'},
      {'name': 'Chibok', 'headquarters': 'Chibok'},
      {'name': 'Damboa', 'headquarters': 'Damboa'},
      {'name': 'Dikwa', 'headquarters': 'Dikwa'},
      {'name': 'Gubio', 'headquarters': 'Gubio'},
      {'name': 'Guzamala', 'headquarters': 'Guzamala'},
      {'name': 'Gwoza', 'headquarters': 'Gwoza'},
      {'name': 'Hawul', 'headquarters': 'Hawul'},
      {'name': 'Jere', 'headquarters': 'Jere'},
      {'name': 'Kaga', 'headquarters': 'Benisheik'},
      {'name': 'Kala/Balge', 'headquarters': 'Rann'},
      {'name': 'Konduga', 'headquarters': 'Konduga'},
      {'name': 'Kukawa', 'headquarters': 'Kukawa'},
      {'name': 'Kwaya Kusar', 'headquarters': 'Kwaya Kusar'},
      {'name': 'Mafa', 'headquarters': 'Mafa'},
      {'name': 'Magumeri', 'headquarters': 'Magumeri'},
      {'name': 'Maiduguri', 'headquarters': 'Maiduguri'},
      {'name': 'Marte', 'headquarters': 'Marte'},
      {'name': 'Mobbar', 'headquarters': 'Damasak'},
      {'name': 'Monguno', 'headquarters': 'Monguno'},
      {'name': 'Ngala', 'headquarters': 'Ngala'},
      {'name': 'Nganzai', 'headquarters': 'Nganzai'},
      {'name': 'Shani', 'headquarters': 'Shani'},
    ],
    'Cross River': [
      {'name': 'Abi', 'headquarters': 'Itigidi'},
      {'name': 'Akamkpa', 'headquarters': 'Akamkpa'},
      {'name': 'Akpabuyo', 'headquarters': 'Ikot Nakanda'},
      {'name': 'Bakassi', 'headquarters': 'Abana'},
      {'name': 'Bekwarra', 'headquarters': 'Abuochiche'},
      {'name': 'Biase', 'headquarters': 'Akpet Central'},
      {'name': 'Boki', 'headquarters': 'Boki'},
      {'name': 'Calabar Municipal', 'headquarters': 'Calabar'},
      {'name': 'Calabar South', 'headquarters': 'Calabar'},
      {'name': 'Etung', 'headquarters': 'Effraya'},
      {'name': 'Ikom', 'headquarters': 'Ikom'},
      {'name': 'Obanliku', 'headquarters': 'Sankwala'},
      {'name': 'Obubra', 'headquarters': 'Obubra'},
      {'name': 'Obudu', 'headquarters': 'Obudu'},
      {'name': 'Odukpani', 'headquarters': 'Odukpani'},
      {'name': 'Ogoja', 'headquarters': 'Ogoja'},
      {'name': 'Yakurr', 'headquarters': 'Ugep'},
      {'name': 'Yala', 'headquarters': 'Okpoma'},
    ],
    'Delta': [
      {'name': 'Aniocha North', 'headquarters': 'Issele-Uku'},
      {'name': 'Aniocha South', 'headquarters': 'Ogwashi-Uku'},
      {'name': 'Bomadi', 'headquarters': 'Bomadi'},
      {'name': 'Burutu', 'headquarters': 'Burutu'},
      {'name': 'Ethiope East', 'headquarters': 'Isiokolo'},
      {'name': 'Ethiope West', 'headquarters': 'Oghara'},
      {'name': 'Ika North East', 'headquarters': 'Owa-Oyibu'},
      {'name': 'Ika South', 'headquarters': 'Agbor'},
      {'name': 'Isoko North', 'headquarters': 'Ozoro'},
      {'name': 'Isoko South', 'headquarters': 'Oleh'},
      {'name': 'Ndokwa East', 'headquarters': 'Aboh'},
      {'name': 'Ndokwa West', 'headquarters': 'Kwale'},
      {'name': 'Okpe', 'headquarters': 'Sapele'},
      {'name': 'Oshimili North', 'headquarters': 'Akwukwu-Igbo'},
      {'name': 'Oshimili South', 'headquarters': 'Asaba'},
      {'name': 'Patani', 'headquarters': 'Patani'},
      {'name': 'Sapele', 'headquarters': 'Sapele'},
      {'name': 'Udu', 'headquarters': 'Udu'},
      {'name': 'Ughelli North', 'headquarters': 'Ughelli'},
      {'name': 'Ughelli South', 'headquarters': 'Otu-Jeremi'},
      {'name': 'Ukwuani', 'headquarters': 'Obiaruku'},
      {'name': 'Uvwie', 'headquarters': 'Effurun'},
      {'name': 'Warri North', 'headquarters': 'Koko'},
      {'name': 'Warri South', 'headquarters': 'Warri'},
      {'name': 'Warri South West', 'headquarters': 'Ogbe-Ijoh'},
    ],
    'Ebonyi': [
      {'name': 'Abakaliki', 'headquarters': 'Abakaliki'},
      {'name': 'Afikpo North', 'headquarters': 'Afikpo'},
      {'name': 'Afikpo South', 'headquarters': 'Owutu Edda'},
      {'name': 'Ebonyi', 'headquarters': 'Onueke'},
      {'name': 'Ezza North', 'headquarters': 'Effium'},
      {'name': 'Ezza South', 'headquarters': 'Onueke'},
      {'name': 'Ikwo', 'headquarters': 'Ikwo'},
      {'name': 'Ishielu', 'headquarters': 'Ezillo'},
      {'name': 'Ivo', 'headquarters': 'Isiagu'},
      {'name': 'Izzi', 'headquarters': 'Iboko'},
      {'name': 'Ohaozara', 'headquarters': 'Obiozara'},
      {'name': 'Ohaukwu', 'headquarters': 'Ezzamgbo'},
      {'name': 'Onicha', 'headquarters': 'Onicha'},
    ],
    'Edo': [
      {'name': 'Akoko-Edo', 'headquarters': 'Igarra'},
      {'name': 'Egor', 'headquarters': 'Uselu'},
      {'name': 'Esan Central', 'headquarters': 'Irrua'},
      {'name': 'Esan North-East', 'headquarters': 'Uromi'},
      {'name': 'Esan South-East', 'headquarters': 'Ubiaja'},
      {'name': 'Esan West', 'headquarters': 'Ekpoma'},
      {'name': 'Etsako Central', 'headquarters': 'Fugar'},
      {'name': 'Etsako East', 'headquarters': 'Agenebode'},
      {'name': 'Etsako West', 'headquarters': 'Auchi'},
      {'name': 'Igueben', 'headquarters': 'Igueben'},
      {'name': 'Ikpoba-Okha', 'headquarters': 'Idogbo'},
      {'name': 'Oredo', 'headquarters': 'Benin City'},
      {'name': 'Orhionmwon', 'headquarters': 'Abudu'},
      {'name': 'Ovia North-East', 'headquarters': 'Okada'},
      {'name': 'Ovia South-West', 'headquarters': 'Igbanke'},
      {'name': 'Owan East', 'headquarters': 'Afuze'},
      {'name': 'Owan West', 'headquarters': 'Sabongida-Ora'},
      {'name': 'Uhunmwonde', 'headquarters': 'Ehor'},
    ],
    'Ekiti': [
      {'name': 'Ado-Ekiti', 'headquarters': 'Ado-Ekiti'},
      {'name': 'Efon', 'headquarters': 'Efon-Alaaye'},
      {'name': 'Ekiti East', 'headquarters': 'Omuo-Ekiti'},
      {'name': 'Ekiti South-West', 'headquarters': 'Ilawe-Ekiti'},
      {'name': 'Ekiti West', 'headquarters': 'Aramoko-Ekiti'},
      {'name': 'Emure', 'headquarters': 'Emure-Ekiti'},
      {'name': 'Gbonyin', 'headquarters': 'Ode-Ekiti'},
      {'name': 'Ido-Osi', 'headquarters': 'Ido-Ekiti'},
      {'name': 'Ijero', 'headquarters': 'Ijero-Ekiti'},
      {'name': 'Ikere', 'headquarters': 'Ikere-Ekiti'},
      {'name': 'Ikole', 'headquarters': 'Ikole-Ekiti'},
      {'name': 'Ilejemeje', 'headquarters': 'Iye-Ekiti'},
      {'name': 'Irepodun/Ifelodun', 'headquarters': 'Igede-Ekiti'},
      {'name': 'Ise/Orun', 'headquarters': 'Ise-Ekiti'},
      {'name': 'Moba', 'headquarters': 'Otun-Ekiti'},
      {'name': 'Oye', 'headquarters': 'Oye-Ekiti'},
    ],
    'Enugu': [
      {'name': 'Aninri', 'headquarters': 'Ndiabor'},
      {'name': 'Awgu', 'headquarters': 'Awgu'},
      {'name': 'Enugu East', 'headquarters': 'Nkwo Nike'},
      {'name': 'Enugu North', 'headquarters': 'Ogui Urban'},
      {'name': 'Enugu South', 'headquarters': 'Uwani'},
      {'name': 'Ezeagu', 'headquarters': 'Aguobu-Owa'},
      {'name': 'Igbo-Etiti', 'headquarters': 'Ogbede'},
      {'name': 'Igbo-Eze North', 'headquarters': 'Enugu-Ezike'},
      {'name': 'Igbo-Eze South', 'headquarters': 'Ibagwa-Aka'},
      {'name': 'Isi-Uzo', 'headquarters': 'Ikem'},
      {'name': 'Nkanu East', 'headquarters': 'Amagunze'},
      {'name': 'Nkanu West', 'headquarters': 'Agbani'},
      {'name': 'Nsukka', 'headquarters': 'Nsukka'},
      {'name': 'Oji River', 'headquarters': 'Oji River'},
      {'name': 'Udenu', 'headquarters': 'Obollo-Afor'},
      {'name': 'Udi', 'headquarters': 'Udi'},
      {'name': 'Uzo-Uwani', 'headquarters': 'Nimbo'},
    ],
    'FCT': [
      {'name': 'Abaji', 'headquarters': 'Abaji'},
      {'name': 'Bwari', 'headquarters': 'Bwari'},
      {'name': 'Gwagwalada', 'headquarters': 'Gwagwalada'},
      {'name': 'Kuje', 'headquarters': 'Kuje'},
      {'name': 'Kwali', 'headquarters': 'Kwali'},
      {'name': 'Municipal', 'headquarters': 'Abuja'},
    ],
    'Gombe': [
      {'name': 'Akko', 'headquarters': 'Akko'},
      {'name': 'Balanga', 'headquarters': 'Balanga'},
      {'name': 'Billiri', 'headquarters': 'Billiri'},
      {'name': 'Dukku', 'headquarters': 'Dukku'},
      {'name': 'Funakaye', 'headquarters': 'Bajoga'},
      {'name': 'Gombe', 'headquarters': 'Gombe'},
      {'name': 'Kaltungo', 'headquarters': 'Kaltungo'},
      {'name': 'Kwami', 'headquarters': 'Kwami'},
      {'name': 'Nafada', 'headquarters': 'Nafada'},
      {'name': 'Shongom', 'headquarters': 'Shongom'},
      {'name': 'Yamaltu/Deba', 'headquarters': 'Deba'},
    ],
    'Imo': [
      {'name': 'Aboh Mbaise', 'headquarters': 'Aboh Mbaise'},
      {'name': 'Ahiazu Mbaise', 'headquarters': 'Ahiazu Mbaise'},
      {'name': 'Ehime Mbano', 'headquarters': 'Ehime Mbano'},
      {'name': 'Ezinihitte Mbaise', 'headquarters': 'Itu'},
      {'name': 'Ideato North', 'headquarters': 'Urualla'},
      {'name': 'Ideato South', 'headquarters': 'Dikenafai'},
      {'name': 'Ihitte/Uboma', 'headquarters': 'Isinweke'},
      {'name': 'Ikeduru', 'headquarters': 'Iho'},
      {'name': 'Isiala Mbano', 'headquarters': 'Umuelemai'},
      {'name': 'Isu', 'headquarters': 'Umundugba'},
      {'name': 'Mbaitoli', 'headquarters': 'Nwaorieubi'},
      {'name': 'Ngor-Okpala', 'headquarters': 'Umuneke'},
      {'name': 'Njaba', 'headquarters': 'Nnenasa'},
      {'name': 'Nkwerre', 'headquarters': 'Nkwerre'},
      {'name': 'Nwangele', 'headquarters': 'Lar'},
      {'name': 'Obowo', 'headquarters': 'Otoko'},
      {'name': 'Oguta', 'headquarters': 'Oguta'},
      {'name': 'Ohaji/Egbema', 'headquarters': 'Ohaji'},
      {'name': 'Okigwe', 'headquarters': 'Okigwe'},
      {'name': 'Onuimo', 'headquarters': 'Okwe'},
      {'name': 'Orlu', 'headquarters': 'Orlu'},
      {'name': 'Orsu', 'headquarters': 'Awo-Omamma'},
      {'name': 'Oru East', 'headquarters': 'Omuma'},
      {'name': 'Oru West', 'headquarters': 'Mgbidi'},
      {'name': 'Owerri Municipal', 'headquarters': 'Owerri'},
      {'name': 'Owerri North', 'headquarters': 'Orie Uratta'},
      {'name': 'Owerri West', 'headquarters': 'Umuguma'},
    ],
    'Jigawa': [
      {'name': 'Auyo', 'headquarters': 'Auyo'},
      {'name': 'Babura', 'headquarters': 'Babura'},
      {'name': 'Biriniwa', 'headquarters': 'Biriniwa'},
      {'name': 'Birnin Kudu', 'headquarters': 'Birnin Kudu'},
      {'name': 'Buji', 'headquarters': 'Buji'},
      {'name': 'Dutse', 'headquarters': 'Dutse'},
      {'name': 'Gagarawa', 'headquarters': 'Gagarawa'},
      {'name': 'Garki', 'headquarters': 'Garki'},
      {'name': 'Gumel', 'headquarters': 'Gumel'},
      {'name': 'Guri', 'headquarters': 'Guri'},
      {'name': 'Gwaram', 'headquarters': 'Gwaram'},
      {'name': 'Gwiwa', 'headquarters': 'Gwiwa'},
      {'name': 'Hadejia', 'headquarters': 'Hadejia'},
      {'name': 'Jahun', 'headquarters': 'Jahun'},
      {'name': 'Kafin Hausa', 'headquarters': 'Kafin Hausa'},
      {'name': 'Kaugama', 'headquarters': 'Kaugama'},
      {'name': 'Kazaure', 'headquarters': 'Kazaure'},
      {'name': 'Kiri Kasama', 'headquarters': 'Kiri Kasama'},
      {'name': 'Kiyawa', 'headquarters': 'Kiyawa'},
      {'name': 'Maigatari', 'headquarters': 'Maigatari'},
      {'name': 'Malam Madori', 'headquarters': 'Malam Madori'},
      {'name': 'Miga', 'headquarters': 'Miga'},
      {'name': 'Ringim', 'headquarters': 'Ringim'},
      {'name': 'Roni', 'headquarters': 'Roni'},
      {'name': 'Sule Tankarkar', 'headquarters': 'Sule Tankarkar'},
      {'name': 'Taura', 'headquarters': 'Taura'},
      {'name': 'Yankwashi', 'headquarters': 'Yankwashi'},
    ],
    'Kaduna': [
      {'name': 'Birnin Gwari', 'headquarters': 'Birnin Gwari'},
      {'name': 'Chikun', 'headquarters': 'Kujama'},
      {'name': 'Giwa', 'headquarters': 'Giwa'},
      {'name': 'Igabi', 'headquarters': 'Turunku'},
      {'name': 'Ikara', 'headquarters': 'Ikara'},
      {'name': 'Jaba', 'headquarters': 'Kwoi'},
      {'name': 'Jema\'a', 'headquarters': 'Kafanchan'},
      {'name': 'Kachia', 'headquarters': 'Kachia'},
      {'name': 'Kaduna North', 'headquarters': 'Kaduna'},
      {'name': 'Kaduna South', 'headquarters': 'Kaduna'},
      {'name': 'Kagarko', 'headquarters': 'Kagarko'},
      {'name': 'Kajuru', 'headquarters': 'Kajuru'},
      {'name': 'Kaura', 'headquarters': 'Kaura'},
      {'name': 'Kauru', 'headquarters': 'Kauru'},
      {'name': 'Kubau', 'headquarters': 'Kubau'},
      {'name': 'Kudan', 'headquarters': 'Kudan'},
      {'name': 'Lere', 'headquarters': 'Lere'},
      {'name': 'Makarfi', 'headquarters': 'Makarfi'},
      {'name': 'Sabon Gari', 'headquarters': 'Sabon Gari'},
      {'name': 'Sanga', 'headquarters': 'Gwantu'},
      {'name': 'Soba', 'headquarters': 'Soba'},
      {'name': 'Zangon Kataf', 'headquarters': 'Zonkwa'},
      {'name': 'Zaria', 'headquarters': 'Zaria'},
    ],
    'Kano': [
      {'name': 'Ajingi', 'headquarters': 'Ajingi'},
      {'name': 'Albasu', 'headquarters': 'Albasu'},
      {'name': 'Bagwai', 'headquarters': 'Bagwai'},
      {'name': 'Bebeji', 'headquarters': 'Bebeji'},
      {'name': 'Bichi', 'headquarters': 'Bichi'},
      {'name': 'Bunkure', 'headquarters': 'Bunkure'},
      {'name': 'Dala', 'headquarters': 'Dala'},
      {'name': 'Dambatta', 'headquarters': 'Dambatta'},
      {'name': 'Dawakin Kudu', 'headquarters': 'Dawakin Kudu'},
      {'name': 'Dawakin Tofa', 'headquarters': 'Dawakin Tofa'},
      {'name': 'Doguwa', 'headquarters': 'Doguwa'},
      {'name': 'Fagge', 'headquarters': 'Fagge'},
      {'name': 'Gabasawa', 'headquarters': 'Gabasawa'},
      {'name': 'Garko', 'headquarters': 'Garko'},
      {'name': 'Garun Mallam', 'headquarters': 'Garun Mallam'},
      {'name': 'Gaya', 'headquarters': 'Gaya'},
      {'name': 'Gezawa', 'headquarters': 'Gezawa'},
      {'name': 'Gwale', 'headquarters': 'Gwale'},
      {'name': 'Gwarzo', 'headquarters': 'Gwarzo'},
      {'name': 'Kabo', 'headquarters': 'Kabo'},
      {'name': 'Kano Municipal', 'headquarters': 'Kano'},
      {'name': 'Karaye', 'headquarters': 'Karaye'},
      {'name': 'Kibiya', 'headquarters': 'Kibiya'},
      {'name': 'Kiru', 'headquarters': 'Kiru'},
      {'name': 'Kumbotso', 'headquarters': 'Kumbotso'},
      {'name': 'Kunchi', 'headquarters': 'Kunchi'},
      {'name': 'Kura', 'headquarters': 'Kura'},
      {'name': 'Madobi', 'headquarters': 'Madobi'},
      {'name': 'Makoda', 'headquarters': 'Makoda'},
      {'name': 'Minjibir', 'headquarters': 'Minjibir'},
      {'name': 'Nassarawa', 'headquarters': 'Nassarawa'},
      {'name': 'Rano', 'headquarters': 'Rano'},
      {'name': 'Rimin Gado', 'headquarters': 'Rimin Gado'},
      {'name': 'Rogo', 'headquarters': 'Rogo'},
      {'name': 'Shanono', 'headquarters': 'Shanono'},
      {'name': 'Sumaila', 'headquarters': 'Sumaila'},
      {'name': 'Takai', 'headquarters': 'Takai'},
      {'name': 'Tarauni', 'headquarters': 'Tarauni'},
      {'name': 'Tofa', 'headquarters': 'Tofa'},
      {'name': 'Tsanyawa', 'headquarters': 'Tsanyawa'},
      {'name': 'Tudun Wada', 'headquarters': 'Tudun Wada'},
      {'name': 'Ungogo', 'headquarters': 'Ungogo'},
      {'name': 'Warawa', 'headquarters': 'Warawa'},
      {'name': 'Wudil', 'headquarters': 'Wudil'},
    ],
    'Katsina': [
      {'name': 'Bakori', 'headquarters': 'Bakori'},
      {'name': 'Batagarawa', 'headquarters': 'Batagarawa'},
      {'name': 'Batsari', 'headquarters': 'Batsari'},
      {'name': 'Baure', 'headquarters': 'Baure'},
      {'name': 'Bindawa', 'headquarters': 'Bindawa'},
      {'name': 'Charanchi', 'headquarters': 'Charanchi'},
      {'name': 'Dan Musa', 'headquarters': 'Dan Musa'},
      {'name': 'Dandume', 'headquarters': 'Dandume'},
      {'name': 'Danja', 'headquarters': 'Danja'},
      {'name': 'Daura', 'headquarters': 'Daura'},
      {'name': 'Dutsi', 'headquarters': 'Dutsi'},
      {'name': 'Dutsin-Ma', 'headquarters': 'Dutsin-Ma'},
      {'name': 'Faskari', 'headquarters': 'Faskari'},
      {'name': 'Funtua', 'headquarters': 'Funtua'},
      {'name': 'Ingawa', 'headquarters': 'Ingawa'},
      {'name': 'Jibia', 'headquarters': 'Jibia'},
      {'name': 'Kafur', 'headquarters': 'Kafur'},
      {'name': 'Kaita', 'headquarters': 'Kaita'},
      {'name': 'Kankara', 'headquarters': 'Kankara'},
      {'name': 'Kankia', 'headquarters': 'Kankia'},
      {'name': 'Katsina', 'headquarters': 'Katsina'},
      {'name': 'Kurfi', 'headquarters': 'Kurfi'},
      {'name': 'Kusada', 'headquarters': 'Kusada'},
      {'name': 'Mai\'Adua', 'headquarters': 'Mai\'Adua'},
      {'name': 'Malumfashi', 'headquarters': 'Malumfashi'},
      {'name': 'Mani', 'headquarters': 'Mani'},
      {'name': 'Mashi', 'headquarters': 'Mashi'},
      {'name': 'Matazu', 'headquarters': 'Matazu'},
      {'name': 'Musawa', 'headquarters': 'Musawa'},
      {'name': 'Rimi', 'headquarters': 'Rimi'},
      {'name': 'Sabuwa', 'headquarters': 'Sabuwa'},
      {'name': 'Safana', 'headquarters': 'Safana'},
      {'name': 'Sandamu', 'headquarters': 'Sandamu'},
      {'name': 'Zango', 'headquarters': 'Zango'},
    ],
    'Kebbi': [
      {'name': 'Aleiro', 'headquarters': 'Aleiro'},
      {'name': 'Arewa Dandi', 'headquarters': 'Arewa'},
      {'name': 'Argungu', 'headquarters': 'Argungu'},
      {'name': 'Augie', 'headquarters': 'Augie'},
      {'name': 'Bagudo', 'headquarters': 'Bagudo'},
      {'name': 'Birnin Kebbi', 'headquarters': 'Birnin Kebbi'},
      {'name': 'Bunza', 'headquarters': 'Bunza'},
      {'name': 'Dandi', 'headquarters': 'Kamba'},
      {'name': 'Fakai', 'headquarters': 'Fakai'},
      {'name': 'Gwandu', 'headquarters': 'Gwandu'},
      {'name': 'Jega', 'headquarters': 'Jega'},
      {'name': 'Kalgo', 'headquarters': 'Kalgo'},
      {'name': 'Koko/Besse', 'headquarters': 'Koko'},
      {'name': 'Maiyama', 'headquarters': 'Maiyama'},
      {'name': 'Ngaski', 'headquarters': 'Ngaski'},
      {'name': 'Sakaba', 'headquarters': 'Sakaba'},
      {'name': 'Shanga', 'headquarters': 'Shanga'},
      {'name': 'Suru', 'headquarters': 'Suru'},
      {'name': 'Wasagu/Danko', 'headquarters': 'Wasagu'},
      {'name': 'Yauri', 'headquarters': 'Yauri'},
      {'name': 'Zuru', 'headquarters': 'Zuru'},
    ],
    'Kogi': [
      {'name': 'Adavi', 'headquarters': 'Ogaminana'},
      {'name': 'Ajaokuta', 'headquarters': 'Ajaokuta'},
      {'name': 'Ankpa', 'headquarters': 'Ankpa'},
      {'name': 'Bassa', 'headquarters': 'Oguma'},
      {'name': 'Dekina', 'headquarters': 'Dekina'},
      {'name': 'Ibaji', 'headquarters': 'Ibaji'},
      {'name': 'Idah', 'headquarters': 'Idah'},
      {'name': 'Igalamela-Odolu', 'headquarters': 'Ajaka'},
      {'name': 'Ijumu', 'headquarters': 'Iyara'},
      {'name': 'Kabba/Bunu', 'headquarters': 'Kabba'},
      {'name': 'Kogi', 'headquarters': 'Koton Karfe'},
      {'name': 'Lokoja', 'headquarters': 'Lokoja'},
      {'name': 'Mopa-Muro', 'headquarters': 'Mopa'},
      {'name': 'Ofu', 'headquarters': 'Ofu'},
      {'name': 'Ogori/Magongo', 'headquarters': 'Ogori'},
      {'name': 'Okehi', 'headquarters': 'Okehi'},
      {'name': 'Okene', 'headquarters': 'Okene'},
      {'name': 'Olamaboro', 'headquarters': 'Olamaboro'},
      {'name': 'Omala', 'headquarters': 'Abejukolo'},
      {'name': 'Yagba East', 'headquarters': 'Isanlu'},
      {'name': 'Yagba West', 'headquarters': 'Odo-Ere'},
    ],
    'Kwara': [
      {'name': 'Asa', 'headquarters': 'Afon'},
      {'name': 'Baruten', 'headquarters': 'Okuta'},
      {'name': 'Edu', 'headquarters': 'Lafiagi'},
      {'name': 'Ekiti', 'headquarters': 'Araromi-Opin'},
      {'name': 'Ifelodun', 'headquarters': 'Share'},
      {'name': 'Ilorin East', 'headquarters': 'Oke-Oyi'},
      {'name': 'Ilorin South', 'headquarters': 'Fufu'},
      {'name': 'Ilorin West', 'headquarters': 'Ilorin'},
      {'name': 'Irepodun', 'headquarters': 'Omu-Aran'},
      {'name': 'Isin', 'headquarters': 'Owu-Isin'},
      {'name': 'Kaiama', 'headquarters': 'Kaiama'},
      {'name': 'Moro', 'headquarters': 'Bode Saadu'},
      {'name': 'Offa', 'headquarters': 'Offa'},
      {'name': 'Oke Ero', 'headquarters': 'Iloffa'},
      {'name': 'Oyun', 'headquarters': 'Ilemona'},
      {'name': 'Patigi', 'headquarters': 'Patigi'},
    ],
    'Lagos': [
      {'name': 'Agege', 'headquarters': 'Agege'},
      {'name': 'Ajeromi-Ifelodun', 'headquarters': 'Ajeromi'},
      {'name': 'Alimosho', 'headquarters': 'Alimosho'},
      {'name': 'Amuwo-Odofin', 'headquarters': 'Festac Town'},
      {'name': 'Apapa', 'headquarters': 'Apapa'},
      {'name': 'Badagry', 'headquarters': 'Badagry'},
      {'name': 'Epe', 'headquarters': 'Epe'},
      {'name': 'Eti-Osa', 'headquarters': 'Ikoyi'},
      {'name': 'Ibeju-Lekki', 'headquarters': 'Ibeju'},
      {'name': 'Ifako-Ijaiye', 'headquarters': 'Ifako'},
      {'name': 'Ikeja', 'headquarters': 'Ikeja'},
      {'name': 'Ikorodu', 'headquarters': 'Ikorodu'},
      {'name': 'Kosofe', 'headquarters': 'Kosofe'},
      {'name': 'Lagos Island', 'headquarters': 'Lagos Island'},
      {'name': 'Lagos Mainland', 'headquarters': 'Yaba'},
      {'name': 'Mushin', 'headquarters': 'Mushin'},
      {'name': 'Ojo', 'headquarters': 'Ojo'},
      {'name': 'Oshodi-Isolo', 'headquarters': 'Oshodi'},
      {'name': 'Shomolu', 'headquarters': 'Shomolu'},
      {'name': 'Surulere', 'headquarters': 'Surulere'},
    ],
    'Nasarawa': [
      {'name': 'Akwanga', 'headquarters': 'Akwanga'},
      {'name': 'Awe', 'headquarters': 'Awe'},
      {'name': 'Doma', 'headquarters': 'Doma'},
      {'name': 'Karu', 'headquarters': 'Karu'},
      {'name': 'Keana', 'headquarters': 'Keana'},
      {'name': 'Keffi', 'headquarters': 'Keffi'},
      {'name': 'Kokona', 'headquarters': 'Garaku'},
      {'name': 'Lafia', 'headquarters': 'Lafia'},
      {'name': 'Nasarawa', 'headquarters': 'Nasarawa'},
      {'name': 'Nasarawa Egon', 'headquarters': 'Nasarawa Egon'},
      {'name': 'Obi', 'headquarters': 'Obi'},
      {'name': 'Toto', 'headquarters': 'Toto'},
      {'name': 'Wamba', 'headquarters': 'Wamba'},
    ],
    'Niger': [
      {'name': 'Agaie', 'headquarters': 'Agaie'},
      {'name': 'Agwara', 'headquarters': 'Agwara'},
      {'name': 'Bida', 'headquarters': 'Bida'},
      {'name': 'Borgu', 'headquarters': 'New Bussa'},
      {'name': 'Bosso', 'headquarters': 'Bosso'},
      {'name': 'Chanchaga', 'headquarters': 'Minna'},
      {'name': 'Edati', 'headquarters': 'Enagi'},
      {'name': 'Gbako', 'headquarters': 'Lemu'},
      {'name': 'Gurara', 'headquarters': 'Izom'},
      {'name': 'Katcha', 'headquarters': 'Katcha'},
      {'name': 'Kontagora', 'headquarters': 'Kontagora'},
      {'name': 'Lapai', 'headquarters': 'Lapai'},
      {'name': 'Lavun', 'headquarters': 'Kutigi'},
      {'name': 'Magama', 'headquarters': 'Nasko'},
      {'name': 'Mariga', 'headquarters': 'Bangi'},
      {'name': 'Mashegu', 'headquarters': 'Mashegu'},
      {'name': 'Mokwa', 'headquarters': 'Mokwa'},
      {'name': 'Munya', 'headquarters': 'Sarkin Pawa'},
      {'name': 'Paikoro', 'headquarters': 'Paikoro'},
      {'name': 'Rafi', 'headquarters': 'Kagara'},
      {'name': 'Rijau', 'headquarters': 'Rijau'},
      {'name': 'Shiroro', 'headquarters': 'Kuta'},
      {'name': 'Suleja', 'headquarters': 'Suleja'},
      {'name': 'Tafa', 'headquarters': 'Tafa'},
      {'name': 'Wushishi', 'headquarters': 'Wushishi'},
    ],
    'Ogun': [
      {'name': 'Abeokuta North', 'headquarters': 'Akomoje'},
      {'name': 'Abeokuta South', 'headquarters': 'Ake'},
      {'name': 'Ado-Odo/Ota', 'headquarters': 'Ota'},
      {'name': 'Egbado North', 'headquarters': 'Ayetoro'},
      {'name': 'Egbado South', 'headquarters': 'Ilaro'},
      {'name': 'Ewekoro', 'headquarters': 'Ewekoro'},
      {'name': 'Ifo', 'headquarters': 'Ifo'},
      {'name': 'Ijebu East', 'headquarters': 'Ogbere'},
      {'name': 'Ijebu North', 'headquarters': 'Ijebu-Igbo'},
      {'name': 'Ijebu North East', 'headquarters': 'Atan'},
      {'name': 'Ijebu Ode', 'headquarters': 'Ijebu-Ode'},
      {'name': 'Ikenne', 'headquarters': 'Ikenne'},
      {'name': 'Imeko Afon', 'headquarters': 'Imeko'},
      {'name': 'Ipokia', 'headquarters': 'Ipokia'},
      {'name': 'Obafemi Owode', 'headquarters': 'Owode-Egba'},
      {'name': 'Odeda', 'headquarters': 'Odeda'},
      {'name': 'Odogbolu', 'headquarters': 'Odogbolu'},
      {'name': 'Ogun Waterside', 'headquarters': 'Abigi'},
      {'name': 'Remo North', 'headquarters': 'Isara-Remo'},
      {'name': 'Sagamu', 'headquarters': 'Sagamu'},
    ],
    'Ondo': [
      {'name': 'Akoko North-East', 'headquarters': 'Ikare'},
      {'name': 'Akoko North-West', 'headquarters': 'Okeagbe'},
      {'name': 'Akoko South-East', 'headquarters': 'Isua'},
      {'name': 'Akoko South-West', 'headquarters': 'Oka'},
      {'name': 'Akure North', 'headquarters': 'Iju/Itaogbolu'},
      {'name': 'Akure South', 'headquarters': 'Akure'},
      {'name': 'Ese-Odo', 'headquarters': 'Igbekebo'},
      {'name': 'Idanre', 'headquarters': 'Owena'},
      {'name': 'Ifedore', 'headquarters': 'Igbara-Oke'},
      {'name': 'Ilaje', 'headquarters': 'Igbokoda'},
      {'name': 'Ile Oluji/Okeigbo', 'headquarters': 'Ile-Oluji'},
      {'name': 'Irele', 'headquarters': 'Ode-Irele'},
      {'name': 'Odigbo', 'headquarters': 'Ore'},
      {'name': 'Okitipupa', 'headquarters': 'Okitipupa'},
      {'name': 'Ondo East', 'headquarters': 'Bolorunduro'},
      {'name': 'Ondo West', 'headquarters': 'Ondo'},
      {'name': 'Ose', 'headquarters': 'Ifon'},
      {'name': 'Owo', 'headquarters': 'Owo'},
    ],
    'Osun': [
      {'name': 'Aiyedaade', 'headquarters': 'Gbongan'},
      {'name': 'Aiyedire', 'headquarters': 'Ile-Ogbo'},
      {'name': 'Atakunmosa East', 'headquarters': 'Iperindo'},
      {'name': 'Atakunmosa West', 'headquarters': 'Osu'},
      {'name': 'Boluwaduro', 'headquarters': 'Otan-Ayegbaju'},
      {'name': 'Boripe', 'headquarters': 'Iragbiji'},
      {'name': 'Ede North', 'headquarters': 'Ede'},
      {'name': 'Ede South', 'headquarters': 'Ede'},
      {'name': 'Egbedore', 'headquarters': 'Awo'},
      {'name': 'Ejigbo', 'headquarters': 'Ejigbo'},
      {'name': 'Ife Central', 'headquarters': 'Ile-Ife'},
      {'name': 'Ife East', 'headquarters': 'Oke-Ogbo'},
      {'name': 'Ife North', 'headquarters': 'Ipetumodu'},
      {'name': 'Ife South', 'headquarters': 'Ifetedo'},
      {'name': 'Ifedayo', 'headquarters': 'Oke-Ila'},
      {'name': 'Ifelodun', 'headquarters': 'Ikirun'},
      {'name': 'Ila', 'headquarters': 'Ila Orangun'},
      {'name': 'Ilesa East', 'headquarters': 'Ilesa'},
      {'name': 'Ilesa West', 'headquarters': 'Ilesa'},
      {'name': 'Irepodun', 'headquarters': 'Ilobu'},
      {'name': 'Irewole', 'headquarters': 'Ikire'},
      {'name': 'Isokan', 'headquarters': 'Apomu'},
      {'name': 'Iwo', 'headquarters': 'Iwo'},
      {'name': 'Obokun', 'headquarters': 'Ibokun'},
      {'name': 'Odo Otin', 'headquarters': 'Okuku'},
      {'name': 'Ola Oluwa', 'headquarters': 'Bode Osi'},
      {'name': 'Olorunda', 'headquarters': 'Igbona'},
      {'name': 'Oriade', 'headquarters': 'Ijesha-Isu'},
      {'name': 'Orolu', 'headquarters': 'Ifon-Osun'},
      {'name': 'Osogbo', 'headquarters': 'Osogbo'},
    ],
    'Oyo': [
      {'name': 'Afijio', 'headquarters': 'Jobele'},
      {'name': 'Akinyele', 'headquarters': 'Moniya'},
      {'name': 'Atiba', 'headquarters': 'Oyo'},
      {'name': 'Atisbo', 'headquarters': 'Tede'},
      {'name': 'Egbeda', 'headquarters': 'Egbeda'},
      {'name': 'Ibadan North', 'headquarters': 'Agodi-Gate'},
      {'name': 'Ibadan North-East', 'headquarters': 'Iwo Road'},
      {'name': 'Ibadan North-West', 'headquarters': 'Onireke'},
      {'name': 'Ibadan South-East', 'headquarters': 'Mapo'},
      {'name': 'Ibadan South-West', 'headquarters': 'Oluyole'},
      {'name': 'Ibarapa Central', 'headquarters': 'Igbo-Ora'},
      {'name': 'Ibarapa East', 'headquarters': 'Eruwa'},
      {'name': 'Ibarapa North', 'headquarters': 'Ayete'},
      {'name': 'Ido', 'headquarters': 'Ido'},
      {'name': 'Irepo', 'headquarters': 'Kishi'},
      {'name': 'Iseyin', 'headquarters': 'Iseyin'},
      {'name': 'Itesiwaju', 'headquarters': 'Otu'},
      {'name': 'Iwajowa', 'headquarters': 'Iwere-Ile'},
      {'name': 'Kajola', 'headquarters': 'Okeho'},
      {'name': 'Lagelu', 'headquarters': 'Iyana-Offa'},
      {'name': 'Ogbomoso North', 'headquarters': 'Ogbomoso'},
      {'name': 'Ogbomoso South', 'headquarters': 'Arowomole'},
      {'name': 'Ogo Oluwa', 'headquarters': 'Ajaawa'},
      {'name': 'Olorunsogo', 'headquarters': 'Igbeti'},
      {'name': 'Oluyole', 'headquarters': 'Idi-Ayunre'},
      {'name': 'Ona Ara', 'headquarters': 'Akanran'},
      {'name': 'Orelope', 'headquarters': 'Igboho'},
      {'name': 'Ori Ire', 'headquarters': 'Ikoyi-Ile'},
      {'name': 'Oyo East', 'headquarters': 'Kosobo'},
      {'name': 'Oyo West', 'headquarters': 'Ojongbodu'},
      {'name': 'Saki East', 'headquarters': 'Ago-Amodu'},
      {'name': 'Saki West', 'headquarters': 'Saki'},
      {'name': 'Surulere', 'headquarters': 'Iresa-Adu'},
    ],
    'Plateau': [
      {'name': 'Barkin Ladi', 'headquarters': 'Barkin Ladi'},
      {'name': 'Bassa', 'headquarters': 'Bassa'},
      {'name': 'Bokkos', 'headquarters': 'Bokkos'},
      {'name': 'Jos East', 'headquarters': 'Angware'},
      {'name': 'Jos North', 'headquarters': 'Jos'},
      {'name': 'Jos South', 'headquarters': 'Bukuru'},
      {'name': 'Kanam', 'headquarters': 'Dengi'},
      {'name': 'Kanke', 'headquarters': 'Kwal'},
      {'name': 'Langtang North', 'headquarters': 'Langtang'},
      {'name': 'Langtang South', 'headquarters': 'Shendam'},
      {'name': 'Mangu', 'headquarters': 'Mangu'},
      {'name': 'Mikang', 'headquarters': 'Mikang'},
      {'name': 'Pankshin', 'headquarters': 'Pankshin'},
      {'name': 'Qua\'an Pan', 'headquarters': 'Namu'},
      {'name': 'Riyom', 'headquarters': 'Riyom'},
      {'name': 'Shendam', 'headquarters': 'Shendam'},
      {'name': 'Wase', 'headquarters': 'Wase'},
    ],
    'Rivers': [
      {'name': 'Abua/Odual', 'headquarters': 'Abua'},
      {'name': 'Ahoada East', 'headquarters': 'Ahoada'},
      {'name': 'Ahoada West', 'headquarters': 'Akinima'},
      {'name': 'Akuku-Toru', 'headquarters': 'Abonnema'},
      {'name': 'Andoni', 'headquarters': 'Ngo'},
      {'name': 'Asari-Toru', 'headquarters': 'Buguma'},
      {'name': 'Bonny', 'headquarters': 'Bonny'},
      {'name': 'Degema', 'headquarters': 'Degema'},
      {'name': 'Eleme', 'headquarters': 'Ogale'},
      {'name': 'Emohua', 'headquarters': 'Emohua'},
      {'name': 'Etche', 'headquarters': 'Okehi'},
      {'name': 'Gokana', 'headquarters': 'Kpor'},
      {'name': 'Ikwerre', 'headquarters': 'Isiokpo'},
      {'name': 'Khana', 'headquarters': 'Bori'},
      {'name': 'Obio/Akpor', 'headquarters': 'Rumuodomaya'},
      {'name': 'Ogba/Egbema/Ndoni', 'headquarters': 'Omoku'},
      {'name': 'Ogu/Bolo', 'headquarters': 'Ogu'},
      {'name': 'Okrika', 'headquarters': 'Okrika'},
      {'name': 'Omuma', 'headquarters': 'Omuma'},
      {'name': 'Opobo/Nkoro', 'headquarters': 'Opobo'},
      {'name': 'Oyigbo', 'headquarters': 'Oyigbo'},
      {'name': 'Port Harcourt', 'headquarters': 'Port Harcourt'},
      {'name': 'Tai', 'headquarters': 'Sakpenwa'},
    ],
    'Sokoto': [
      {'name': 'Binji', 'headquarters': 'Binji'},
      {'name': 'Bodinga', 'headquarters': 'Bodinga'},
      {'name': 'Dange Shuni', 'headquarters': 'Dange'},
      {'name': 'Gada', 'headquarters': 'Gada'},
      {'name': 'Goronyo', 'headquarters': 'Goronyo'},
      {'name': 'Gudu', 'headquarters': 'Gudu'},
      {'name': 'Gwadabawa', 'headquarters': 'Gwadabawa'},
      {'name': 'Illela', 'headquarters': 'Illela'},
      {'name': 'Isa', 'headquarters': 'Isa'},
      {'name': 'Kebbe', 'headquarters': 'Kebbe'},
      {'name': 'Kware', 'headquarters': 'Kware'},
      {'name': 'Rabah', 'headquarters': 'Rabah'},
      {'name': 'Sabon Birni', 'headquarters': 'Sabon Birni'},
      {'name': 'Shagari', 'headquarters': 'Shagari'},
      {'name': 'Silame', 'headquarters': 'Silame'},
      {'name': 'Sokoto North', 'headquarters': 'Sokoto'},
      {'name': 'Sokoto South', 'headquarters': 'Sokoto'},
      {'name': 'Tambuwal', 'headquarters': 'Tambuwal'},
      {'name': 'Tangaza', 'headquarters': 'Tangaza'},
      {'name': 'Tureta', 'headquarters': 'Tureta'},
      {'name': 'Wamako', 'headquarters': 'Wamako'},
      {'name': 'Wurno', 'headquarters': 'Wurno'},
      {'name': 'Yabo', 'headquarters': 'Yabo'},
    ],
    'Taraba': [
      {'name': 'Ardo Kola', 'headquarters': 'Sunkani'},
      {'name': 'Bali', 'headquarters': 'Bali'},
      {'name': 'Donga', 'headquarters': 'Donga'},
      {'name': 'Gashaka', 'headquarters': 'Serti'},
      {'name': 'Gassol', 'headquarters': 'Mutum Biyu'},
      {'name': 'Ibi', 'headquarters': 'Ibi'},
      {'name': 'Jalingo', 'headquarters': 'Jalingo'},
      {'name': 'Karim Lamido', 'headquarters': 'Karim Lamido'},
      {'name': 'Kumi', 'headquarters': 'Jenuwa Kogi'},
      {'name': 'Lau', 'headquarters': 'Lau'},
      {'name': 'Sardauna', 'headquarters': 'Gembu'},
      {'name': 'Takum', 'headquarters': 'Takum'},
      {'name': 'Ussa', 'headquarters': 'Lissam'},
      {'name': 'Wukari', 'headquarters': 'Wukari'},
      {'name': 'Yorro', 'headquarters': 'Yorro'},
      {'name': 'Zing', 'headquarters': 'Zing'},
    ],
    'Yobe': [
      {'name': 'Bade', 'headquarters': 'Gashua'},
      {'name': 'Bursari', 'headquarters': 'Damaturu'},
      {'name': 'Damaturu', 'headquarters': 'Damaturu'},
      {'name': 'Fika', 'headquarters': 'Fika'},
      {'name': 'Fune', 'headquarters': 'Damagum'},
      {'name': 'Geidam', 'headquarters': 'Geidam'},
      {'name': 'Gujba', 'headquarters': 'Gujba'},
      {'name': 'Gulani', 'headquarters': 'Gulani'},
      {'name': 'Jakusko', 'headquarters': 'Jakusko'},
      {'name': 'Karasuwa', 'headquarters': 'Karasuwa'},
      {'name': 'Machina', 'headquarters': 'Machina'},
      {'name': 'Nangere', 'headquarters': 'Nangere'},
      {'name': 'Nguru', 'headquarters': 'Nguru'},
      {'name': 'Potiskum', 'headquarters': 'Potiskum'},
      {'name': 'Tarmuwa', 'headquarters': 'Damagum'},
      {'name': 'Yunusari', 'headquarters': 'Yunusari'},
      {'name': 'Yusufari', 'headquarters': 'Yusufari'},
    ],
    'Zamfara': [
      {'name': 'Anka', 'headquarters': 'Anka'},
      {'name': 'Bakura', 'headquarters': 'Bakura'},
      {'name': 'Birnin Magaji/Kiyaw', 'headquarters': 'Birnin Magaji'},
      {'name': 'Bukkuyum', 'headquarters': 'Bukkuyum'},
      {'name': 'Bungudu', 'headquarters': 'Bungudu'},
      {'name': 'Gummi', 'headquarters': 'Gummi'},
      {'name': 'Gusau', 'headquarters': 'Gusau'},
      {'name': 'Kaura Namoda', 'headquarters': 'Kaura Namoda'},
      {'name': 'Maradun', 'headquarters': 'Maradun'},
      {'name': 'Maru', 'headquarters': 'Maru'},
      {'name': 'Shinkafi', 'headquarters': 'Shinkafi'},
      {'name': 'Talata Mafara', 'headquarters': 'Talata Mafara'},
      {'name': 'Tsafe', 'headquarters': 'Tsafe'},
      {'name': 'Zurmi', 'headquarters': 'Zurmi'},
    ],
  };

  /// Get list of LGAs for a given state
  static List<String> getLgasForState(String state) {
    final lgas = lgasByState[state] ?? [];
    return lgas.map((lga) => lga['name']!).toList();
  }

  /// Get headquarters for a given LGA
  static String? getHeadquartersForLga(String state, String lga) {
    final lgas = lgasByState[state] ?? [];
    final lgaData = lgas.firstWhere(
      (l) => l['name'] == lga,
      orElse: () => {'name': '', 'headquarters': ''},
    );
    return lgaData['headquarters'];
  }
}
